services:
  frontend:
    container_name: react_frontend_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: "${VITE_API_URL}"
        VITE_API_BASE_URL: "${VITE_API_BASE_URL}"
    ports:
      - "3032:8080"
    restart: unless-stopped
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
