FROM node:24.11.1-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias con npm
RUN npm install

# Copiar el resto del proyecto
COPY . .

EXPOSE 3032

# Usar npm run dev en lugar de pnpm
CMD ["npm", "run", "dev", "--", "--host"]