export const QUERY_KEYS = {
  orders: "orders",
  orderDetail: "orderDetail",
  dashboardOrders: "dashboardOrders",
  myServices: "myServices",
  dashboardMetrics: "dashboardMetrics",
  technicians: "technicians",
  clients: "clients",
  modules: "modules",
  roles: "roles",
  users: "users",
  inventory: "inventory",
  equipment: "equipment",
  services: "services",
  supplies: "supplies",
  tools: "tools",
  maintenanceTypes: "maintenanceTypes",
  clientCompanies: "clientCompanies",
  profile: "profile",
  metrics: "metrics",
};
